### PR TITLE
Add QuickJS-ng replacing QuickJS

### PR DESCRIPTION
**Pull request by saghul**
Ref: https://github.com/GoogleChromeLabs/jsvu/issues/141

### CODE REVIEW

**Comment by saghul** [comment]
Updated the README too. @mathiasbynens this one should be ready for review!

**Review by mathiasbynens — APPROVED** [review]

**Comment by saghul** [comment]
Any chance a release could be made, so we can recommend users to install it this way? Thank you!

**Comment by mathiasbynens** [comment]
It already happened :) This should be part of v2.2.0. Thanks a lot for your contribution!

**Comment by saghul** [comment]
😱 that was fast, cheers!

**Pull request merged**
